image: node:latest

services:
  - redis:4.0.0

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

connect:
  image: redis
  script:
  - redis-cli -h redis PING

test:
  script:
    - yarn test
